import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CodeBlock } from "@/components/code-block";

const architectureDiagram = `
+------------------------+      +--------------------------+      +-------------------------+
|   Operating System     |      |   AuthGuard OS Module    |      |    Firebase Backend     |
| (Login Manager)        |      |  (Node.js/Python/Java)   |      |   (Cloud Functions)     |
+------------------------+      +--------------------------+      +-------------------------+
           |                              |                               |
           | 1. User enters credentials   |                               |
           |----------------------------->|                               |
           |                              | 2. verifyCredentials() API call |
           |                              |------------------------------>|
           |                              |                               | 3. Validate against
           |                              |                               |    Firebase Auth &
           |                              |                               |    Firestore
           |                              |                               |
           |                              |              4. Needs MFA?    |
           |                              |<------------------------------|
           |                              |                               |
           | 5. initiateMFA()             |                               |
           |<-----------------------------|                               |
           |                              |                               |
           | 6. User provides OTP/link... |                               |
           |----------------------------->|                               |
           |                              | 7. validateToken() API call   |
           |                              |------------------------------>|
           |                              |                               | 8. Verify token
           |                              |                               |
           |                              |     9. Generate Custom Token  |
           |                              |<------------------------------|
           |                              |                               |
           | 10. Return session token     |                               |
           |<-----------------------------|                               |
           |                              |                               |
           | 11. Log auth event           | 12. logAuthEvent()            |
           |----------------------------->|------------------------------>| 13. Store in Firestore
           |                              |                               |   'auth_logs' collection
`;

export default function ArchitecturePage() {
  return (
    <div className="space-y-8">
      <PageHeader
        title="System Architecture"
        description="A visual representation of how AuthGuard OS integrates with an operating system and Firebase."
      />

      <Card>
        <CardHeader>
          <CardTitle>Architecture Diagram</CardTitle>
        </CardHeader>
        <CardContent>
          <CodeBlock code={architectureDiagram} lang="text" />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Authentication Model</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="font-semibold text-lg mb-2">Primary Authentication</h3>
            <p className="text-muted-foreground">
              Core user identity is managed through Firebase Authentication, supporting standard email/password and phone number/OTP sign-in methods. This provides a robust and scalable foundation for user management.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-lg mb-2">Multi-Factor Authentication (MFA)</h3>
            <p className="text-muted-foreground">
              An additional security layer is built on top of the primary authentication. The specific MFA state and configuration for each user are stored in the Firestore database, allowing for flexible and user-specific security policies. Supported factors include OTPs, email verification links, and hardware-based device keys.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-lg mb-2">Session Management</h3>
            <p className="text-muted-foreground">
              Upon successful verification of all required factors, a custom Firebase Authentication token is generated by a secure Cloud Function. This token has a limited lifetime and is sent back to the OS login manager. The client-side OS module is responsible for managing this token, refreshing it when necessary, and using it to authenticate subsequent requests, ensuring that the user's session remains secure and valid.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
